### PR TITLE
Precheck confirm button checks eligibility every time

### PR DESCRIPTION
**Pull request by tacataca**
We now do a check of precheck eligibility when the user clicks confirm. If the user is not eligible on time of clicking confirm, they are redirected to a status page with a message notifying what to do next.

This avoids issues like user opening email, then leaving open over night and the user not being pre check eligible any more because its too late, or because some other detail changed between email being sent and user confirming.

### CODE REVIEW

**Comment by tacataca** [comment]
Woops, killed codeship with that force push
https://app.codeship.com/projects/168813/builds/41860656?pipeline=1f1198ac-43c6-4152-9e25-d11cadf0d8b6

**Comment by tacataca** [comment]
Woops, killed codeship integration with the force push 🤔

**Comment by tacataca** [comment]
That test that failed uncovered a behaviour that we probably want.

The reject path should only check if the application is **too late** (instead of any precheck condition), as it renders a status page explaining the existing eligibility errors, where the user can send a message to the staff.

By checking for any precheck condition not being met, we never show the form to send message to staff.

**Comment by sheldond** [comment]
@tacataca Oh! You are right, I'm sorry, I forgot about that! 🤦‍♂ 

Another important piece to check on the reject path is whether the family is already checked in or not (we wouldn't want the status to go back to changes requested if the family was previously checked in).

So I think we would have to check the conditions `not_checked_in_already?` and `not_too_late?`, right?

**Comment by tacataca** [comment]
This got quite confusing to me.

General Scenario - Page was left open for a week, clicks the button reject:

1. Application was already approved: _Should not allow to reject_
2. An attendee in the family has already checked in: _Should not allow to reject_
3. The precheck window has closed: _Should not allow to reject_

Does this sound right to you?

The not_checked_in_already? method is confusing me, I think it wont work to cover 1 and 2.

**Pull request merged**
